<?php

/**
 * @file
 * Install, update, and uninstall functions for the Workbench Notify module.
 */

/**
 * Implements hook_uninstall().
 */
function workbench_notify_uninstall() {
  variable_del('workbench_notify_transition_state');
  variable_del('workbench_notify_roles');
  variable_del('workbench_notify_from');
  variable_del('workbench_notify_subject');
  variable_del('workbench_notify_message');
  variable_del('workbench_notify_display_message');
}
