<?php
/**
 * @file
 * Code for the Albatross Events feature.
 */

include_once('flight_events.features.inc');

/**
 * Implements hook_menu()
 **/
function flight_events_menu() {
  $items['events'] = array(
    'title' => 'Events',
    'page callback' => 'flight_events_front',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Blank callback wrapper for the homepage.
 **/
function flight_events_front() {
  return ' ';
}
