<?php

/*function flight_city_custom_theme($initialize = FALSE) {
  $custom_theme = &drupal_static(__FUNCTION__);
  dpm(arg(0));
  dpm($ar)
  return $custom_theme;
}*/

/**
 * Implements hook_menu()
 **/
function flight_city_config_menu() {
  $items['external-service/%'] = array(
    'title' => 'Embed code',
    'page callback' => 'flight_city_config_external_service',
    'page arguments' => array(1),
    'access arguments' => array('view the administration theme'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/*function flight_city_config_theme($region) {
  return array(
    'flight_city_config_external_service_html' => array(
      'template' => 'templates/external-service-html',
    ),
    'flight_city_config_external_service_html_full' => array(
      'template' => 'templates/external-service-html-full',
    ),
  );
}*/

function flight_city_config_external_service($region) {
  dpm($region);
  switch($region) {
    case 'header':
      return ' ';
      break;
    default: 
      dpm('yeah');
      return MENU_NOT_FOUND;
  }
}


function flight_city_config_preprocess_page(&$vars) {
  //dpm($vars);
  if(in_array('page__external_service', $vars['theme_hook_suggestions'])) {
    dpm($vars);
  };
}

function flight_city_config_preprocess_html(&$vars) {
  
  
  //dpm($vars);
}


function flight_city_config_navbar() {
  $items = array();

  // The 'Home' tab is a simple link, which is wrapped in markup associated
  // with a visual tab styling.
  $items['help'] = array(
    '#type' => 'navbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Help'),
      '#href' => 'http://www.baltimore.ifsight.com/help#page-title',
      '#options' => array(
        'attributes' => array(
          'title' => t('My Workbench'),
          'class' => array('navbar-icon', 'navbar-icon-help'),
        ),
      ),
    ),
    '#weight' => 1000,
  );

  

  return $items;
}

/**
 * Implements hook_form_alter.
 * File customizations.
 */
function flight_city_config_form_alter(&$form, $form_state, $form_id) {
  if (strpos($form_id, 'media_edit_') !== FALSE || $form_id === 'file_entity_add_upload') {
    // Hide the domain selection option when uploading files.
    if (!empty($form['domain_file']) && !user_access('administer files')) {
      $form['domain_file']['#access'] = FALSE;
    }

    // Make the alt field required
    $form['field_file_image_alt_text'][$form['field_file_image_alt_text']['#language']][0]['value']['#required'] = TRUE;

    // Set the submit function to Redirect to the workbench file list if this is a multiedit field.
    if (arg(3) === 'edit-multiple') {
      $form['actions']['submit']['#submit'][] = 'flight_city_config_media_edit_form_submit';
    }
  }

  dpm($form_id);

}

/**
 * Implements hook_form_submit.
 * Redirect to the workbench file list.
 */
function flight_city_config_media_edit_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'admin/workbench/files';
}

/**
 * Implements hook_form_alter.
 * Hide the domain selection option when uploading files.
 */
function flight_city_config_form_file_entity_add_upload_alter(&$form, $form_state) {
  if (!empty($form['domain_file']) && !user_access('administer files')) {
    $form['domain_file']['#access'] = FALSE;
  }
}