<?php
/**
 * @file
 * Code for the Flight City Events feature.
 */

include_once 'flight_city_events.features.inc';


/**
 * Implements hook_menu()
 **/
function flight_city_events_menu() {
  $items['events'] = array(
    'title' => 'Events',
    'page callback' => 'flight_city_events_front',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Blank callback wrapper for the homepage.
 **/
function flight_city_events_front() {
  return ' ';
}
